services:
  app:
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/home/app/.bundle/
      - vendor_ruby:/home/app/vendor/ruby
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
  postgresql:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
