FROM ruby:3.3.11-slim

WORKDIR /rails

RUN apt-get update && \
    apt-get install -y \
      build-essential \
      git \
      curl \
      libpq-dev \
      postgresql-client \
      libyaml-dev \
      pkg-config

RUN gem install bundler:2.5.22

COPY Gemfile Gemfile.lock ./

RUN bundle install --jobs=4 --retry=3

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
