services:
  app:
    environment:
      RAILS_ENV: development
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true
  postgresql:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  sidekiq:
    environment:
      RAILS_ENV: development
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
